### PR TITLE
master-qa-16928

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-16928

### CODE REVIEW

**Comment by lesliewong92** [comment]
Test Test

**Comment by lwongyt** [comment]
Testing Testing 456

**Comment by lwongyt** [comment]
Testing Testing 789

**Comment by lwongyt** [comment]
Testing Testing 101112

**Comment by lwongyt** [comment]
This is a test

**Comment by lwongyt** [comment]
This is a test

**Comment by lwongyt** [comment]
This is a test

**Comment by lwongyt** [comment]
This is a test

**Comment by lwongyt** [comment]
This is a test

**Pull request closed without merging**
